server:
  port: 5004

eureka:
  client:
    service-url:
       defaultZone: http://127.0.0.1:6001/eureka/       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。

spring:
  application:
    name: provider-user-hystrix
